api:
  build: .
  volumes:
    - ./app:/home/current/app
  command: npm start #top -b
  external_links:
    - mfdata_postgres_1:postgres
    - mfdata_eventstore_1:eventstore
  environment:
    DEBUG: true
    NODE_ENV: development
    APPLICATION_NAME: Api
